apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plannerrun-chart.fullname" . }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}