apiVersion: v1
kind: Secret
metadata:
  name: planner-secrets
type: Opaque
data:
  BASE_URL:          {{ .Values.secrets.BASE_URL         | toString | b64enc | quote }}
  DB_NAME:           {{ .Values.secrets.DB_NAME          | toString | b64enc | quote }}
  DB_USER:           {{ .Values.secrets.DB_USER          | toString | b64enc | quote }}
  DB_PASSWORD:       {{ .Values.secrets.DB_PASSWORD      | toString | b64enc | quote }}
  SMTP_SERVER:       {{ .Values.secrets.SMTP_SERVER      | toString | b64enc | quote }}
  SMTP_PORT:         {{ .Values.secrets.SMTP_PORT        | toString | b64enc | quote }}
  SENDER_EMAIL:      {{ .Values.secrets.SENDER_EMAIL     | toString | b64enc | quote }}
  APP_PASSWORD:      {{ .Values.secrets.APP_PASSWORD     | toString | b64enc | quote }}
  STRIPE_API_KEY:    {{ .Values.secrets.STRIPE_API_KEY   | toString | b64enc | quote }}
  PRICE_ID_3_MONTHS: {{ .Values.secrets.PRICE_ID_3_MONTHS| toString | b64enc | quote }}
  PRICE_ID_4_MONTHS: {{ .Values.secrets.PRICE_ID_4_MONTHS| toString | b64enc | quote }}
  PRICE_ID_5_MONTHS: {{ .Values.secrets.PRICE_ID_5_MONTHS| toString | b64enc | quote }}
  PRICE_ID_6_MONTHS: {{ .Values.secrets.PRICE_ID_6_MONTHS| toString | b64enc | quote }}
